# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/deepin-qt-dbus-factory.spec

# add or remove files that should be synced
synced_files:
    - rpm/deepin-qt-dbus-factory.spec
    - .packit.yaml

upstream_package_name: dde-qt-dbus-factory
# downstream (Fedora) RPM package name
downstream_package_name: deepin-qt-dbus-factory

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"0,/Version:/ s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/deepin-qt-dbus-factory.spec"
  post-upstream-clone: |
    cp rpm/dde-qt-dbus-factory.spec rpm/deepin-qt-dbus-factory.spec

